### ISSUE TITLE
getting an error  (has no attribute 'find)

### ISSUE THREAD

**Issue by malosaa** [theimperium20/Aliexpress-Review-Crawler#2]
Hi i did try it but i get this error 

regards 

D:\Aliexpress-Review-Crawler>py crawler-windows.py
Traceback (most recent call last):
  File "crawler-windows.py", line 197, in <module>
    AliexpressCrawler(pages,URL,product_handle,filename)
  File "crawler-windows.py", line 50, in AliexpressCrawler
    rating = ( soup.find('div',{'class':'product-star-order util-clearfix'}) ).f
ind-all('span' , {'class' , 'percent-num' }).text  #AVERAGE PRODUCT RATING
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by khaledkoubaa** [comment]
me too:
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by ilia2s** [comment]
Aliexpress rating div's classes was changed. You need to modify parser code to use it with current versions of aliexpress HTML code
