### ISSUE TITLE
eror when run

### ISSUE THREAD

**Issue by grootoo** [theimperium20/Aliexpress-Review-Crawler#3]
i got an error like this, i already set the url

URL = "https://www.aliexpress.com/item/4000461503980.html"
product_handle = 'WOOCOMMERS'
pages = 3
filename = "scrapt.csv"

Traceback (most recent call last):
  File "d:\Aliexpress\bot_rahul\Aliexpress-Review-Crawler-master\crawler-windows.py", line 222, in <module>
    AliexpressCrawler(pages, URL, product_handle, filename)
  File "d:\Aliexpress\bot_rahul\Aliexpress-Review-Crawler-master\crawler-windows.py", line 39, in AliexpressCrawler
    soup = BeautifulSoup(r.content, "lxml")
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\bs4\__init__.py", line 245, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

**Comment by ilia2s** [comment]
> i got an error like this, i already set the url
> 
> URL = "https://www.aliexpress.com/item/4000461503980.html" product_handle = 'WOOCOMMERS' pages = 3 filename = "scrapt.csv"
> 
> Traceback (most recent call last): File "d:\Aliexpress\bot_rahul\Aliexpress-Review-Crawler-master\crawler-windows.py", line 222, in AliexpressCrawler(pages, URL, product_handle, filename) File "d:\Aliexpress\bot_rahul\Aliexpress-Review-Crawler-master\crawler-windows.py", line 39, in AliexpressCrawler soup = BeautifulSoup(r.content, "lxml") File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\bs4__init__.py", line 245, in **init** raise FeatureNotFound( bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

you need to install bs4 pip library, see readme at the mainpage
